library(dplyr)
library(lubridate)
dir <- "./household_power_consumption.txt"
full <- read.table(dir, header=T, sep=";", stringsAsFactors = F, na.strings="?")
data <- subset(full, Date=="1/2/2007" | Date =="2/2/2007")
data1 <- mutate(data, datetime = dmy(Date) + hms(Time))
par(mfrow = c(2,2), cex=.6)
with(data1, {
    plot(datetime, Global_active_power, type="l", ylab="Global Active Power", xlab="")
    plot(datetime, Voltage, type="l")
    plot(data1$datetime, data1$Sub_metering_1, type="n", ylab="Energy sub metering", xlab="")
    lines(data1$datetime, data1$Sub_metering_1)
    lines(data1$datetime, data1$Sub_metering_2, col="red")
    lines(data1$datetime, data1$Sub_metering_3, col="blue")
    legend("topright", lty=1, col=c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), bty="n")
    plot(datetime, Global_reactive_power, type="l", ylim=c(0.0, 0.5))
})
dev.copy(png, file="plot4.png")
dev.off()