library(dplyr)
library(lubridate)
dir <- "./household_power_consumption.txt"
full <- read.table(dir, header=T, sep=";", stringsAsFactors = F, na.strings="?")
data <- subset(full, Date=="1/2/2007" | Date =="2/2/2007")
data1 <- mutate(data, datetime = dmy(Date) + hms(Time))
plot(data1$datetime, data1$Sub_metering_1, type="n", ylab="Energy sub metering", xlab="")
lines(data1$datetime, data1$Sub_metering_1)
lines(data1$datetime, data1$Sub_metering_2, col="red")
lines(data1$datetime, data1$Sub_metering_3, col="blue")
legend("topright", lty=1, col=c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png, file="plot3.png")
dev.off()